version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-247-177-254.eu-west-1.compute.amazonaws.com
            database: dbklvqvi1tutmf
            schema: cuustomer-new-api$dev
            user: oersrozbwuiumc
            password: dcc2a555df4043d499caf16d9606151b3eea5dfbfd5e9610f6009b8f90db5727
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: false